In [1]:
1+1
1+1


2

In [2]:
## Numpy:
import numpy as np

In [3]:
lst=[1,2,3,4]
arr=np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(4,)

In [6]:
arr1=np.array([[1,2,3],[4,5,6]])

In [7]:
## 2 diamension
arr1.shape

(2, 3)

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [11]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [12]:
###convert Tupale in array
np.array((1,2,3))

array([1, 2, 3])

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr1.dtype

dtype('int32')

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(1,10,2).reshape(5,1)



array([[1],
       [3],
       [5],
       [7],
       [9]])

In [18]:
np.arange(1,10,2).reshape(5,1).shape


(5, 1)

In [19]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
## reverse order
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [21]:
## inbuild fun (equaly space element)
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [22]:
np.linspace(1,20,40).shape

(40,)

In [23]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [24]:
# 1 diamension
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
# 2 diamension
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# 1 diamension
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
# 2 diamension
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# 3 diamension(inner array--(2,8) 2-row,8-colomn)
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [29]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
## Broadcast operation
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [31]:
# identity matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
np.eye(6).shape

(6, 6)

In [33]:
## value ranging between 0 to 1
print("Random num generatin(uniform distribution)")
np.random.rand(2,3)

Random num generatin(uniform distribution)


array([[0.80737142, 0.58404283, 0.70324607],
       [0.38909107, 0.60673393, 0.08278899]])

In [34]:
print("Ramdom num following a normal distribution with mean=0 and std=1")
print(np.random.randn(5,3))

Ramdom num following a normal distribution with mean=0 and std=1
[[ 0.87205716  1.55824721  0.7201705 ]
 [-0.92259796  0.16958809 -0.23552981]
 [-0.51281762 -0.32302416  0.78432759]
 [ 1.17716703 -0.28875086 -1.00176607]
 [ 0.95839174 -0.78360492  1.77191154]]


In [35]:
## select random num between 1 to 100
np.random.randint(1,100)

9

In [36]:
## select 50 random num between 1 to 100
np.random.randint(1,100,50)

array([87, 64, 35,  3, 22, 79,  8, 93, 24, 83, 78, 57, 35, 53, 41, 84, 12,
       26, 54, 98, 14, 64, 23, 40, 49, 32, 66, 50, 88, 94, 59,  8, 49, 98,
       15, 81, 37, 31, 53, 65,  8, 63, 37, 23, 49, 36, 53, 59, 71, 47])

In [37]:
## select random num between 1 to 100 in array form
np.random.randint(1,100,(4,4))

array([[61, 76, 49, 67],
       [16, 79, 27, 73],
       [58, 27, 95, 20],
       [68, 14, 67, 85]])

In [38]:
## slicing
arr=np.arange(0,11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [42]:
## last element
arr[-1:]

array([10])

In [43]:
arr[-1:7:-1]

array([10,  9,  8])

In [44]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [45]:
arr[-1:3:-2]

array([10,  8,  6,  4])

In [46]:
## 2 diamension
arr1=np.random.randint(2,100,20).reshape(5,4)

In [47]:
arr1


array([[67, 51, 60, 64],
       [69, 53, 97, 60],
       [48, 31, 68,  6],
       [93, 41, 69, 36],
       [78, 14, 82, 74]])

In [48]:
arr1[3:4]

array([[93, 41, 69, 36]])

In [49]:
arr1[0:3]

array([[67, 51, 60, 64],
       [69, 53, 97, 60],
       [48, 31, 68,  6]])

In [50]:
arr1[0:3,0:3]

array([[67, 51, 60],
       [69, 53, 97],
       [48, 31, 68]])

In [51]:
arr1[3:,1:]

array([[41, 69, 36],
       [14, 82, 74]])

In [52]:
arr1


array([[67, 51, 60, 64],
       [69, 53, 97, 60],
       [48, 31, 68,  6],
       [93, 41, 69, 36],
       [78, 14, 82, 74]])

In [53]:
arr1[2:4,1:3]

array([[31, 68],
       [41, 69]])

In [54]:
arr1[2:4,:1] 

array([[48],
       [93]])

In [55]:
 arr1[2:4,3:]

array([[ 6],
       [36]])

In [2]:
## universal functions
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

NameError: name 'np' is not defined

In [2]:
arr2

NameError: name 'arr2' is not defined

In [58]:
arr1

array([[24, 49, 73],
       [99, 39, 30],
       [10, 21, 76]])

In [59]:
arr1 + arr2

array([[ 97, 143,  93],
       [142, 136,  92],
       [ 87, 101, 164]])

In [60]:
# multiplication
arr1 * arr2

array([[1752, 4606, 1460],
       [4257, 3783, 1860],
       [ 770, 1680, 6688]])

In [61]:
## division
arr1 / arr2

array([[0.32876712, 0.5212766 , 3.65      ],
       [2.30232558, 0.40206186, 0.48387097],
       [0.12987013, 0.2625    , 0.86363636]])

In [62]:
## square root
np.sqrt(arr1)

array([[4.89897949, 7.        , 8.54400375],
       [9.94987437, 6.244998  , 5.47722558],
       [3.16227766, 4.58257569, 8.71779789]])

In [63]:
np.exp(arr2)

array([[5.05239363e+31, 6.66317622e+40, 4.85165195e+08],
       [4.72783947e+18, 1.33833472e+42, 8.43835667e+26],
       [2.75851345e+33, 5.54062238e+34, 1.65163625e+38]])

In [64]:
np.log10(arr1)

array([[1.38021124, 1.69019608, 1.86332286],
       [1.99563519, 1.59106461, 1.47712125],
       [1.        , 1.32221929, 1.88081359]])

In [65]:
arr1=np.arange(1,10)

In [66]:
arr1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1[2:]=1000

NameError: name 'arr1' is not defined

In [68]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [1]:
np.dot(arr1,arr2)

NameError: name 'np' is not defined

In [ ]:
## matrix multiplication
np.matmul(arr1,arr2)